import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Responsivenav from "@/components/Home/Navbar/Responsivenav";
import Footer from "@/components/Home/footer/Footer";
import Scrolltotop from "@/components/Heper/Scrolltotop";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Full stack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="custom-scrollbar">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div> 
{/* 
        <AnimatedCursor
      innerSize={10}
      outerSize={30}
      
      outerAlpha={0}
      innerScale={0.7}
      outerScale={2}
      innerStyle={
 {background: "white"}
      }
     
     outerStyle={{
      border : "3px solid white"
     }}
    /> */}
        </div>
        <Responsivenav/>
        {children}
        <Footer/>
        <Scrolltotop/>
      </body>
    </html>
  );
}
